config/routes.rb
Rails.application.routes.draw do

  get '/' => 'site#home', as: 'root'
  resources :users

end

app/models/athlete_training.rb
class AthleteTraining < ActiveRecord::Base
end

app/models/training.rb
class Training < ActiveRecord::Base
	#belongs_to :trainer, class_name: "User", foreign_key: "trainer_id"
	#has_and_belongs_to_many :athletes, :class_name => "User", :join_table => "athletes_trainings", :foreing_key => "athlete_id"
	validate :check_role_trainer

	belongs_to :trainer, -> {trainers}, class_name: "User", foreign_key: "trainer_id"

	has_and_belongs_to_many :athletes, -> {athletes}, class_name: "User", :join_table => "athletes_trainings", foreign_key: "athlete_id"


	def check_role_trainer
    	if self.trainer == nil
      		 errors.add(:role, "can't be create trainings")
    	end
  	end
end	

app/models/user.rb
class User < ActiveRecord::Base
	 validates :role, inclusion: { in: %w(trainer athlete)}
	 #validates :role, :password, :email, presence: true

	

	 has_many :trainings, as: :trainer
	 has_and_belongs_to_many :trainings, as: :athletes
	 #has_many :trainings_joined, :class_name => "Training", trough: :athletes_trainings, :foreign_key => "training_id"


	 scope :trainers, -> {where(role: "trainer")}
	 scope :athletes, -> {where(role: "athlete")}

	# has_many :trainings, :class_name => "Training", :foreign_key => "training_id"
	# has_and_belongs_to_many :trainings_joined, :class_name => "Training", :join_table => "athletes_trainings", :foreign_key => "training_id"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	def home
		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.create user_params
	end

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	private
	def user_params
		params.require(:user).permit(:name,:email, :password, :role)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">

    <title> Start Fit Bot Theme</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/copia.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title> Start Fit Bot Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
<!-- Custom Fonts -->
    <link href="/assets/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <!-- Custom CSS -->
    <link href="/assets/css/grayscale.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <!-- <a class="navbar-brand page-scroll" href="#page-top">
                    <i class="fa fa-play-circle"></i>  <span class="light">Start</span> Bootstrap
                </a>-->
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="views/users">Sing Up</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#download">Login</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contacto</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


    <!-- Download Section !☺
    <section id="download" class="content-section text-center">
        <div class="download-section">
            <div class="container">
                <div class="col-lg-8 col-lg-offset-2">
                    <h2>Download Grayscale</h2>
                    <p>You can download Grayscale for free on the preview page at Start Bootstrap.</p>
                    <a href="http://startbootstrap.com/template-overviews/grayscale/" class="btn btn-default btn-lg">Visit Download Page</a>
                </div>
            </div>
        </div>
    </section>

    <section id="contact" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>Contact Start Bootstrap</h2>
                <p>Feel free to email us to provide some feedback on our templates, give us suggestions for new templates and themes, or to just say hello!</p>
                <p><a href="mailto:feedback@startbootstrap.com">feedback@startbootstrap.com</a>
                </p>
                <ul class="list-inline banner-social-buttons">
                    <li>
                        <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                    </li>
                    <li>
                        <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                    </li>
                    <li>
                        <a href="https://plus.google.com/+Startbootstrap/posts" class="btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">Google+</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </section>-->

    <!-- Map Section 
    <div id="map"></div>-->

    <!-- Footer -->

   


<%= yield %>
    <footer>
        <div class="container text-center">
            <p>Copyright &copy; Your Website 2014</p>
        </div>
    </footer>

 <!-- jQuery -->
    <script src="/assets/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/assets/js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="/assets/js/jquery.easing.min.js"></script>

    <!-- Google Maps API Key - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/ -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRngKslUGJTlibkQ3FkfTxj3Xss1UlZDA&sensor=false"></script>

    <!-- Custom Theme JavaScript -->
    <script src="/assets/js/grayscale.js"></script>
</body>
</html>

app/views/site/home.html.erb
 <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand-heading">Fit Bot???</h1>
                        <p class="intro-text">A free, responsive, one page Bootstrap theme.<br>Created by Start Bootstrap.</p>
                        <a href="#about" class="btn btn-circle page-scroll">
                            <i class="fa fa-angle-double-down animated"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- About Section -->
    <section id="about" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>About Grayscale</h2>
                <p>Grayscale is a free Bootstrap 3 theme created by Start Bootstrap. It can be yours right now, simply download the template on <a href="http://startbootstrap.com/template-overviews/grayscale/">the preview page</a>. The theme is open source, and you can use it for any purpose, personal or commercial.</p>
                <p>This theme features stock photos by <a href="http://gratisography.com/">Gratisography</a> along with a custom Google Maps skin courtesy of <a href="http://snazzymaps.com/">Snazzy Maps</a>.</p>
                <p>Grayscale includes full HTML, CSS, and custom JavaScript files along with LESS files for easy customization.</p>
            </div>
        </div>
    </section>

app/views/users/index.html.erb
<ul>
	<% @users.each do |user|%>
	<li><%= link_to user.name, user_path(user.id) %></li>
	<li><%= user.email %></li>
	<li><%= user.role %></li>
	<% end %>
</ul>

<%= link_to "Insert new User", new_user_path%>

app/views/users/new.html.erb
<%= form_for @user do |u| %>
	<%=	u.label :email %>
	<%=	u.text_field :email %>
	<%=	u.label :password %>
	<%=	u.text_field :password %>
	<%=	u.label :role %>
	<%=	u.text_field :role %>
	
	<%= u.submit "Create Trainer" %>
<% end %>

app/views/users/new_athlete.html.erb
<%= form_for @user do |u| %>
	<%=	u.label :name %>
	<%=	u.text_field :name %>
	<%=	u.label :email %>
	<%=	u.text_field :email %>
	<%=	u.label :password %>
	<%=	u.text_field :password %>
	<%=	u.label :role %>
	<%=	u.text_field :role %>
	
	<%= u.submit "Create Athlete" %>
<% end %>

app/views/users/show.html.erb
<p>
  <strong>name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>email:</strong>
  <%= @user.email %>
</p>
 
<p>
  <strong>role:</strong>
  <%= @user.role %>
</p>




<%= link_to "New Athlete" %></br>
<%= link_to "New Training" %></br>

<%= link_to "View Athletes" %></br>
<%= link_to "View Trainings" %></br>